bot.js

Fixed bug that made sample bot crash when not being able to write an emoji

Fixed bug that made sample bot crash when not being able to write an emoji

---

lib/Slackbot_worker.js

This enables support for multiple message types.
For example, the following will now work;
```
bot.reply(message, {"type": "typing"});
setTimeout(function() {
bot.reply(message, "Hello there!");
}, 2000);
```
which will show the bot as typing before sending a response. This is particularly useful when you have to perform some computation before replying after a few seconds.

Support multiple message types

---

lib/SlackBot.js

This PR addresses the `botkit is undefined` error when attempting to implement custom slash-commands. Changing it to `slack_botkit` allows it to work again and I'm assuming that's what was meant to be there.

fixes slash_command and outgoing webhook functions

---

lib/CoreBot.js

Noticed that this checks for the presence of a user id rather than a channel id. :)

fix incorrect variable when checking id

---

readme.md

Assuming issue #7 is a documentation error, this updates the code example for `bot.say()` in the readme with an accurate example value.
The docs on [this page](http://howdy.ai/botkit/docs/#sending-messages) will need the same fix.

Fix param for  bot.say() example code in readme.md

---

lib/CoreBot.js
readme.md

Another PR here! :p
I used to code on Hubot before trying Botkit and lack a feature I did not found (and maybe missed?) which is accessing the data matching the capturing `RegExp` in the `hears()` function, like [here in Hubot](https://hubot.github.com/docs/scripting/#capturing-data)
This PR inject the `match` object into `message` to deal with it more easily in the callback. Maybe I'll add some documentation in the README.
Best

Inject RegExp match into message

---

lib/storage/redis_storage.js
lib/storage/storage_test.js

Following #38, dunno why, had problems during rebase and ended up by forking again the project to make it possible in a simple clear commit.
Some thoughts:
- I added like I said a `allById()` methods which I find handy. I can totally remove it and implement it back in my project if you find it not suitable for here
- You may add as devDependencies `unit.js`, and maybe `monk` and `redis` to make all the tests pass
- It seems that mongo tests does not let the script hang up, it keeps waiting at the end, maybe good closing the mongo connexion?
Best

Storage | Added Redis storage

---

lib/CoreBot.js
lib/SlackBot.js
lib/Slackbot_worker.js
lib/console_logger.js
package.json
readme.md
test/Slack_web_api-test.js

- Added a configuration option `logger`, which expects an object with a `log` method. 
- The `log` method expects its first argument to be either a string or an integer representing one of the RFC 5424 syslog levels.
- The `log` method accepts a variable number of additional arguments and should try to inspect and log all of them.
- If a `logger` is not supplied to `botkit.slackbot()`, then the default implementation, `ConsoleLogger`, will be used.
- `ConsoleLogger` implements much the same behavior as before, with the addition of log levels.
- `ConsoleLogger` will honor a configuration option `logLevel` supplied to `botkit.slackbot()`. It can be either a string or an integer representing one of the RFC 5424 syslog levels. Any message with a higher log level than the `logLevel` will not …

Add loglevels and an extension point for an external logging provider

---

lib/Slackbot_worker.js

I felt that the bot's replies were pretty jarring / abrupt. I think introducing a slight delay and adding a typing indicator will provide a much smoother and natural user experience. 
I added a method to reply with typing delay based on how long the message is. I also added a method to simply start typing which is useful when calling out to third party apis. 
Let me know what you think.

add reply with typing + start typing

---

readme.md

Installation in readme was missing instructions for installing the dependencies through `npm i`.
#75

Add npm i instructions to readme

---

lib/Slackbot_worker.js

`npm test` gives me `jscs: not found`.

Allows user to specify message id

---

lib/CoreBot.js
lib/events.js
package.json
tests/events.js

I also add also a way to output a log of the `.trigger` actions (ex: `DEBUG=*,-botkit:events:trigger:tick node bot.js` or `DEBUG=botkit:events:trigger:presence_change node bot.js`).
The code that was doing event management was the same in 3 places (copy and pasted)
It also had a mechanism that prevent the unprocessed listeners to execute if a listener return false. This mechanisms is error prone since it depends on the order in which the event listeners (`.on`) are registered. It seemed that the mechanism was not used beside optimization.

Make the code more DRY and more flexible using EventEmitter2

---

lib/Slack_web_api.js

Fix lack of the `cb` parameter on `bot.middleware.post_api` call.

Fix problem with json parameter for middleware call

---

readme.md

This follows several discussions on the chat and discovery of subtle differences between how to pass formatted messages with attachements as input to bot.reply, convo.say and chat.postMessage

Documentation for messages with attachements and initiating private conversation

---

lib/CoreBot.js

When using conversation.say with a message object that had no text but did have an attachment, the undefined text property was still passed to mustache for rendering, throwing a TypeError.
This change adds a simple check that the text exists before attempting to render it, otherwise setting message.text to an empty string (which does not appear in slack output at all - not even a blank line)

Add handling of undefined message object text in conversation.tick

---

lib/CoreBot.js

Adds the pattern matches to the `message` object when handling responses in conversations.
This information is passed along with the message much like it is done with pattern matching in `hears`, saving one additional call to `message.text.match()` when we want to know what exactly were the matching groups (when using regexes).

Add pattern match to message object in convos

---

lib/Slackbot_worker.js

Slack's RTM documentation (https://api.slack.com/rtm) recommends sending a ping every few seconds.  I've encountered an issue with being disconnected while running behind a proxy but others (#104) seemed to have encountered this as well.

Add websocket ping

---

lib/Slack_web_api.js

I sent an email to Slack asking why none of the pins methods were available to bots. Couple days later, they discovered it was a bug and it is now fixed.
So, I thought I'd add those methods to the web api in botkit.

Add pins methods to web_api

---

lib/Slackbot_worker.js

When set with postMessage, the id seems to prevent 
posting messages with the same id (e.g. after slackbot restart)

Only provide slack_message.id if using the RTM API

---

examples/slackbutton_bot.js

If you inspect _bots object the old code, it ends up with only a single key. Using the bot returned by startRTM stores all the bots in _bots correctly.

use bot returned by startRTM

---

lib/Slackbot_worker.js

The slash command `response_url` takes a JSON body, not a form-encoded one. Form encoding will URL encode special characters in the message you're trying to send.

Post JSON to response URL, not form encoded

---

lib/Slackbot_worker.js

It was impossible to specify `unfurl_links: false` or `unfurl_media: false` because they'd get turned into `null` which would result in the default behavior (which was often `true`).

Fix falsy unfurl_links or unfurl_media

---

lib/Slackbot_worker.js
package.json

botkit doesn't work behind a proxy.  The initial call start the RTM session works because the request library automatically checks for HTTP Proxy environment variables.  The websocket library does not do the same thing.  This pull request uses the http-proxy-agent library to add proxy support to the websocket call.  This pull request is for issues #21 (which was closed) and #145.

Add proxy support for web socket connection

---

lib/Slack_web_api.js

Whan call [oauth.access](https://api.slack.com/methods/oauth.access) during [OAuth process](https://api.slack.com/docs/oauth), `slack_api` try to call `callAPIWithoutToken` ([ref](https://github.com/howdyai/botkit/blob/master/lib/Slack_web_api.js#L36)) method but `slack_api` doesn't have such a method (and not defined anywhere).
So I got an error below:
```
TypeError: slack_api.callAPIWithoutToken is not a function
at Object.module.exports.slack_api.oauth.access ...
```
* Defined `callAPIWithoutToken` on `slack_api`
* `slack_botkit.config` has `clientId` or these parameters, so if these parameters were not passed to the method, compose option from `bot.config` by default.
Then, we can call `oauth.access` method as following:
bot.api.oauth.access({code: …

Define callAPIWithoutToken method on slack_api to call oauth.access

---

lib/Slackbot_worker.js
readme.md

Currently there is no way to properly cleanup a spawned worker. This PR adds `bot.destroy()` to cleanup a worker. `destroy()` was added instead of overloading `bot.closeRTM()` since `spawn` is distinct from `bot.startRTM()` and you may want to close and RTM connection and reconnect without tearing down the worker.
Update: I also added logic to detect stale connections if no `PONG` messages have been received.

Add bot.destroy() to prevent memory leaks

---

lib/Slackbot_worker.js
package.json
readme.md

Websocket connections to the Slack RTM API can fail for many reasons. This PR implements exponential backoff retry logic for failed connections if the `retry` property is passed as config to `controller.spawn`. `retry` is the max number of reconnection attempts. It maybe `Infiity` or even `true`. If `true`, it defaults to 3 retry attempts.
NOTE: this PR is based on #157 and should be merged after.

Add Slack Bot Reconnect Capability

---

lib/Slack_web_api.js

The problem here arises in many places, but in our case it happened like this:
1. We called `bot.api.channels.history({..}, someFunction)`. In `someFunction()` there was an error and it throws.
2. In https://github.com/howdyai/botkit/blob/master/lib/Slack_web_api.js#L80 the `.callAPI()` function is called with the callback (someFunction).
3. For some reason there's a try/catch clause around the callback invocation. Now what happens is that `someFunction` throws an error, then `callAPI` catches it, but then calls it again.
You should not wrap a callback invocation with a try/catch.

Do not try/catch the callback and then call it again

---

lib/Facebook.js

no issue
- Move "GOT A MESSAGE HOOK" message into debug output instead of console.log.

Move "MESSAGE HOOK" message into debug output.

---

lib/SlackBot.js

For Slack, the RegExp for mentions and direct_mentions does not match if the message uses the valid <@userId|username> syntax. This PR updates the regex so that botkit will emit mention and direct_mention events if the username is included.
Note: usernames can only be in the set [a-z0-9] so there won't be any special characters that could cause problems constructing a regex including usernames. See https://get.slack.help/hc/en-us/articles/216360827-Changing-your-username

adds support for <@userId|username> syntax for mentions and direct_mentions

---

facebook_bot.js
lib/Facebook.js
lib/storage/storage_test.js
package.json
readme-facebook.md

In addition to CLI-related changes, I fixed a typo in storage_test.js

New CLI options for facebook bot to automatically get localtunnel.me URL

---

examples/demo_bot.js

Was testing out examples, looks like the bot is listening for `dm me`, not `dm`

demo-bot: update comments for dm usage

---

readme-facebook.md

no issue
- Resolves a weird markdown nesting issue when readme-facebook.md is viewed on GitHub.

Correct a formatting issue in readme-facebook.md

---

lib/SlackBot.js

When a user gets redirected back to my app from slack I want to redirect them to a URL called `/team/:team-id`, but I don't have access to the team id. This adds the identity to the request object so that I can access it in the callback.

Make identity available to the user of the OAuth endpoint.

---

lib/SlackBot.js

The idea is to make it possible to configure the webserver static dir.
The variable `__dirname` points to the directory where the SlackBot.js file resides which is usually inside `node_modules`.
```
var controller = Botkit.slackbot({
webserver: {
static_dir: __dirname + '/public'
}
});
```
An alternative (which actually seems better) is to add a new parameter to the `setupWebserver` function.

Webserver static dir can be configured through configuration

---

readme-slack.md

Following the instructions in `readme-slack.md` results in the following error:
```
module.js:338
throw err;
^
Error: Cannot find module '/Users/danielbird/Development/botkit/bot.js'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3
```
Change `token=REPLACE_THIS_WITH_YOUR_TOKEN node bot.js` to `token=REPLACE_THIS_WITH_YOUR_TOKEN node slack_bot.js`.

Use correct name of example bot in readme-slack.md

---

lib/CoreBot.js

Remove an unused variable from the `handle` method in CoreBot.js

Remove unused variable in CoreBot.js

---

lib/CoreBot.js

botkit/lib/CoreBot.js:731 if (match = message.text.match(test)) {
ReferenceError: match is not defined

Fix issue ReferenceError: match is not defined

---

lib/Facebook.js

Allows you to pass a static dir to serve files from for bot using Facebook as well.

Allow a configurable directory to serve static files for Facebook based bots

---

lib/Slackbot_worker.js

I've been debugging some websocket connection issues that we've seen pretty consistently on Beep Boop where the connection lasts 6 or 7 days, then disconnects, and doesn't attempt to reconnect.  I've narrowed this down to the following scenario:
+ websocket connection goes stale, i.e. `PONG` receipt times out
+ attempts to reconnect - but is unsuccessful
+ a `close` event triggers on the websocket with an error code `1006` with this unsuccessful reconnect attept, meaning it was an abormal close ([more info here](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent))
Currently that's where the websocket reconnect attempt stops, so this PR adds another reconnect attempt when an abnormal close event is received on the websocket.  We've seen this fix our slack rtm connections going …

Reconnect when websocket closes abnormally

---

lib/Facebook.js

Update `createWebhookEndpoints` log message to refer to Facebook Messenger Platform instead of Slash commands.

Refer to Messenger Platform in Facebook botkit log

---

lib/middleware/slack_authentication.js

https://github.com/howdyai/botkit/issues/307
There is logging happening here which introduces a reference error on `slack_botkit`. Removed this logging code because it already happens in SlackBot.js.

Issue 307: Fix reference error in slash command processing.

---

lib/Slackbot_worker.js

When responding to slash commands and interactive messages, apps should be able to do so without any content:
https://api.slack.com/slash-commands#responding_to_a_command
https://api.slack.com/docs/message-buttons#how_to_respond_to_message_button_actions
After looking at the existing code, I thought a new public method was the best course of action. Adding this functionality into existing method(s) seemed awkward. For example, I considered adding this to the `replyPrivate` method. There were two things I don't like about that. First, the name of the method would be confusing at this point, and changing the method name would be a breaking change. Second, client code would have to pass `null` for the the `resp` argument, or pass in an additional argument, which would make for a less defined …

Apps should be able to respond with 200 without text.

---

lib/Slackbot_worker.js
readme-slack.md

This pull request adds a new method to `Slackbot_worker.js`: `replyAndUpdate` which allows quick editing of a previously sent reply. 
Which addresses this issue: #156 
(I also snuck in a commit that fixes some linter issues outside of this implementation)
Here is a GIF demonstrating it in action:
I figured that there was so much boilerplate code necessary when updating previously sent messages that it warranted a helper function, and this is what I've come up with.
It takes a `source` message, a `response` message (string or object) (the "_updateable_" - that is, a message which may or may not be updated) and an asynchronous "_updater_" callback which determines how and when to update the "_updateable_" `response` message. Internally, `replyAndUpdate` ensures that a response message with …

Add replyAndUpdate method for updating Slack messages

---

lib/Slackbot_worker.js
readme-slack.md

The implementation on `#replyAndUpdate` is really nice, but I feel like there is going to be some use in exposing the message object from the initial reply. In my use case I use it to delete the message after 5 seconds if the async callback to update the message fails.

Expose the src on #replyAndUpdate()

---

lib/SlackBot.js

Removed some variables that weren't defined.  
```
/home/nodejs/nodeapps/smchatbot/node_modules/botkit/lib/SlackBot.js:69
if (cb) cb(null, bot);
^
ReferenceError: bot is not defined
at Object.Slackbot.slack_botkit.configureSlackApp (/home/nodejs/nodeapps/smchatbot/node_modules/botkit/lib/SlackBot.js:69:30)
at Object.<anonymous> (/home/nodejs/nodeapps/smchatbot/node_modules/botkit/examples/slackbutton_bot.js:39:4)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:134:18)
at node.js:962:3
```
Also, it doesn't appear that there would be any benefit in passing in a callback to that `configureSlackApp()` …

remove 'bot' variables that are not defined

---

lib/CoreBot.js

This simply will consider "n" as a "no" utterance and "y" as a "yes" utterance _only_ if there are no more characters in the string. This protects against conflicts between capturing-options, for instance, when one option matches a word like `'^next`, and another matches "no"utterances so when the user responds with "next", we don't want it to be considered a "no" utterance erroneously.

fix single-character utterances

---

lib/SlackBot.js

Just something minor but bothered me during debugging/exploring.
Cheers,
Deu

Fixed typo on logs, 'interactive message' instead of 'slash command'

---

facebook_bot.js
package.json

According to the [release note](https://github.com/75lb/command-line-args/releases) of command-line-args, there is a breaking change between v2.1.6 and v3.0.0 which will cause runtime error.

Update command-line-args to new API version in facebook_bot.js

---

lib/Slackbot_worker.js
readme-slack.md

Perhaps this is just a personal preference, but I believe that callbacks should only be required for functions that may perform asynchronous operations. For all synchronous functions, requiring a callback to be passed in may mislead devs into thinking that it's asynchronous and requires unnecessary consideration for control flow. Therefore, I made the callbacks optional for `bot.identifyBot()` and `bot.identifyTeam()` because there's absolutely nothing async taking place in those.

don't require callback for synchronous identify functions

---

lib/Facebook.js

FB stickers can be distinguished from regular images sent by the user by looking at the message data for a sticker_id field. Right now, botkit doesn't support plumbing that through so it's impossible to distinguish a Like from someone sending an image. This fixes that issue.

Added FB sticker detection

---

lib/Slack_web_api.js

This change simplifies the creation of the Slack web api interface and reduces the amount of copy paste code.
I also simplified the callbacks in the callAPI and callAPIWithoutToken methods.

simplifies slack web api instantiation

---

lib/CoreBot.js
lib/Facebook.js

The older Facebook endpoint doesn't support (All) Emojis. Using JSON and the new endpoint theres now support :).

Facebook POST message using JSON and newer endpoint to support Emojis.

---

readme.md

I discovered a ton of botkit messages that weren't logging with the default levels in Winston, hence an update to the readme logger example.

Show winston levels being set

---

lib/Slackbot_worker.js

Fixed some observed issues where reconnections would hit a ping/pong error right away.  This was due to the interval and the lastPong from the previous connection not being properly cleaned up.

Slack reconnect cleanup

---

readme.md

Just a simple catch: changed "BotKit" to "Botkit"

Fix typo on readme

---

lib/middleware/slack_authentication.js

The incoming request for an Interactive Message has a different structure than Slash Commands. The authentication middleware should be able to handle this different format. Specifically, the request body has a `payload` JSON string, which contains the token.

Fix authentication for Slack Interactive Messages.

---

readme.md

- Add `var`s so the chained functions are not globally declared
- Change the `response` parameter to `err` in `askFlavor`
- Since `askFlavor` is being passed to `bot.startConversation`, it will
get passed an error object (if there is one), not a response object
- add semicolons

Docs - Fix the example readme code for Multi-Stage Convos

---

.vscode/launch.json
botframework_bot.js
lib/BotFramework.js
lib/Botkit.js
package.json
readme-botframework.md
readme.md

I added a new connector to Botkit that lets it support the Microsoft Bot Framework.  I also wrote an initial set of docs and linked to it from the main readme. This currently adds a dependency to our BotBuilder SDK as it needs the ChatConnector class from the SDK.  We can do work on ourside to break out the ChatConnector as a separate NPM which will lighten the load dependency wise some.

Microsoft Bot Framework Connector, Sample, and Readme

---

lib/Facebook.js

PaaS hosting offerings like Heroku and Azure App Service do not have a standard numerical port, as it's randomly generated when the app is re-started. 
The code currently has a check that ensures the port specified is a number. This will always fail and throw an exception on Heroku and Azure App Service, causing the app the crash. 
Example port from Azure App Service: "\\.\pipe\a59322f5-0005-4a3b-9242-24625191a3f2"
My fix removes the number check as ExpressJS, which is how the bots are served, has no requirement that ports are a number. 
Closes howdyai/botkit#369

Remove integer port requirement for Facebook

---

readme-slack.md

Proposed the use of Api.ai to integrate NLP to a Botkit bot. 
It's even better than wit.ai
the api.ai community made a specific middleware for Botkit which i used in the example.

Use Api.ai's natural language tools in your Botkit-powered Bot!

---

lib/Slackbot_worker.js

The purpose of this PR is to ensure if someone calls `destroy()` on their worker instance, it won't reconnect.  Calling `destroy()` already cancels any pending reconnect attempts, but there's a small chance that the `start.rtm` api call was already issue, but hasn't received a response yet.  In this case what happens is the worker closes out the current RTM connection and cancels any queued up reconnect attempts.  It doesn't currently handle a case where the callback from the `rtm.started` api call comes back after `destroy()` was called.
I added a flag to track the state of if the worker has been _destroyed_ - and then make sure to check that prior to creating the websocket connection for the RTM.  This prevents the case described above.
We've run with this particular patch on a bot with …

Ensure no reconnect happens after destroy()

---

facebook_bot.js
lib/Facebook.js
readme-facebook.md

Adding support for Facebook Notification Settings (Regular Push, Silent Push, Silent)

---

lib/Facebook.js
readme-facebook.md

Add a type field to message to distinguish between 'message_received' and 'postback'

---

readme.md

Adds clarification to addQuestion capture option docs. Must pass empty object if not using capture options
closes #456

Update readme addQuestion() capture options docs

---

examples/slackbutton_bot.js

Adds forgotten line in example so it works as expected
botkit needs redirectUri in config for slackbutton oauth
Pass it into the example bot, check for redirectUri when run
closes #458

Update slackbutton_bot.js example

---

lib/Facebook.js

This fixes Issue #450 
The documentation says `createConversation` should be callable on the bot instance passed to event handlers; the slackbot works exactly as documented.  I read through the code and see no slack-specific reason why createConversation shouldn't work everywhere that startConversation does. Live tests show no problem.
See https://github.com/howdyai/botkit/blob/b4f69f4cb32fc94dc6563e8bb63cedc33e949aa3/lib/Slackbot_worker.js#L297

Make createConversation callable on facebook bot instance

---

lib/Slack_web_api.js

When attachments are sent to these API methods, they need to be handled in the same way. `postMessage` was already doing it, so had `update` do the same.

Slack's `chat.update` should work with attachments

---

lib/CoreBot.js
package.json

Fixes #439.
Uses the `clone` npm package to provide a deep clone. This _probably_ has performance implications since `JSON.parse(JSON.stringify(thing))` is super fast, but I don't think the original implementation meant to throw away `Date` and `Symbol` objects.

Don't use JSON.parse/stringify to clone.

---

lib/SlackBot.js

Not only save bot token but also app access token as some calls need it and it can have different permissions

Also keep app access_token

---

lib/SlackBot.js
readme-slack.md

https://github.com/howdyai/botkit/issues/329
This will enable handling auth flows for various use cases by way of `redirect_uri` query params. 
If we stay with the existing design, I see two approaches:
a) Pass params around and only use them if the Slack App controller is configured with the `redirectUri` value.
b) Pass the entire redirect URI around. This options gives more flexibility in case apps want to have multiple redirect URI endpoints. This might be useful if they want greater control over their auth flows than what Botkit provides.
For the app we're building, we don't have a use case for b), so I thought to try out a) and get some feedback. 
Question (if the approach is ok):
Should the `redirect_params` be passed into the `create/update_team` and `create_bot` events also?

Add flexibility to Slack auth flow via custom redirect params

---

lib/storage/simple_storage.js
readme.md

Add the `delete` method to jfs simple storage integration.
I'm happy to add it to the [storage_test](lib/storage/storage_test.js) but I'm not sure how other storages are implementing delete.

Add delete to simple storage

---

lib/SlackBot.js

I made a bot that impersonates me, but this disabled hearing for my messages.
I can separate my messages from the bot's messages by checking for message.bot_id .

Add hearing for impersonating bots.

---

lib/CoreBot.js

See issue #492. Using a default hostname of 127.0.0.1 overrides the http module's expected default hostname as described here: https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback. This can cause deployment errors on services such as heroku.
> If the hostname is omitted, the server will accept connections on any IPv6 address (::) when IPv6 is available, or any IPv4 address (0.0.0.0) otherwise.

Set 0.0.0.0 to default hostname

---

examples/slackbutton_bot.js
examples/slackbutton_bot_interactivemsg.js
lib/CoreBot.js
lib/SlackBot.js
lib/Slackbot_worker.js
lib/Studio.js
package.json
readme-slack.md

This PR adds support for the events API, along with a few other changes and bug fixes in the Botkit Studio functionality.
This is mostly the same as #480, but a cleaned up merge with some features normalized for maintainability in the future.

Events API support

---

lib/Facebook.js
readme-facebook.md

Add handlers for setting and deleting the Get Started payload

---

lib/Facebook.js
readme-facebook.md

* Add to Facebook readme.
* Add code to /lib/Facebook.js to recognise the messaging_referral webhook and create a corresponding event in botkit, to be used:
```
controller.on('facebook_referral', function(bot, message) {
console.log('the referral code is' + message.referral.ref)
});
```

Add support for Facebook messaging_referral - fixes #518

---

examples/slackbutton_bot.js

Closes #510 
I introduced a bug in #465 by adding `process.env.redirectUri` as a required variable to run slackbutton_bot.js example.
`redirectUri` is an optional parameter that is part of the slackbutton oauth flow, and as such should not be required to run the file.
This removes that requirement, and comments out redirectUri in the bot's config while pointing it out as an optional parameter.

slackbutton_bot.js redirectUri Bug Fix

---

facebook_bot.js
lib/Facebook.js

Yo,
By this PR, i want to bring a new functionality proposed by Facebook to our lovely Botkit :cupid:
Recently, FB let us configure the Thread Settings on Messenger to improve the user experience, by adding  a welcome screen to display a get started button or putting a greeting for the new conversations ... and much more.
Documentation : https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

Integrate facebook thread settings

---

readme-facebook.md

In readme-facebook the documentation was inconsistent with the code, see #560.

message_referral -> facebook_referral

---

examples/slackbutton_bot.js
lib/SlackBot.js

Events API does not pass bot_id to channel_join and group_join events, which we were checking for in order to determine if it was the bot which joined the channel or group. 
This restores expected behavior
I added an exception for channel and group joins to filtering out events associated with our bot user, I think this is the only event we listen to with slack that has our bot's user id as the `user: id` so I think this should be fine for now.
closes #347

Fix bot_channel_join and bot_group_join with Slack Events API

---

lib/Slackbot_worker.js

closes #507 
`bot.send()` is looking for `bot.config.send_via_rtm !== true` which its not finding in `bot.config`. So messages are being sent via web API, and never reaching the rtm.send
However, `bot.botkit.config.send_via_rtm` does exist, once you've passed it into the controller, and this PR changes the logic to look there. 
Also check if `message.type == 'typing'` to send typing indications via rtm.

Slack: fix send_via_rtm, fix typing indicator

---

lib/Slackbot_worker.js
readme-slack.md

A Beep Boop user ran into an issue when on connection and periodic points in time, they were doing A LOT of work that was maxing out CPU so much that it caused node.js's event loop to queue excessively. RTM connections were healthy and returning `pong` responses but the node process wasn't processing the `pong` response in time because the event queue was so backed up. This caused a lot of thrashing of connects/discconects/connects within their process:
Ultimately they need to better manage/throttle the work being done inside of the process, but the mitigation to avoid the connection thrashing was to increase the amount of time considered to consider a connection stale.
An overview of the changes:
- add `stale_connection_timeout` to make stale connection detection configurable. This is …

Make stale connection detection configurable

---

.jscsrc
lib/Facebook.js
lib/SlackBot.js
lib/TwilioIPMBot.js

The goal of this PR is to normalize the way messages flow from incoming webhooks sent by the messaging platforms into botkit-style messages.
I do not intend to change the way these actually work, just to normalize the interfaces that are presented to make it easier for developers who want to integrate Botkit into existing web apps in different ways.
The result should be that devs who want to write their own webhook endpoint can call controller.handleWebhookPayload() and Botkit will handle all the rest.

Refactor handling of incoming messages from webhooks

---

facebook_bot.js
lib/Facebook.js
readme-facebook.md

**Proposed Changes:** add express middleware to webhook POST route to validate incoming requests. Validate the X-HUB signature sent in headers against your Facebook App Secret. Throw an error to abort parsing requests that failed validation. The error is handled by an error handler which responds with a safe error to unvalidated requests. Relies on node's crypto lib. 
Configurable by passing `validate_requests: true, app_secret: your_app_secret` when creating your controller object.
When in production, this prevents an attacker from forcing your application to process huge arrays of requests or impersonate FB/users. FB batches its messages, and so a malicious server could make requests stuffed full of data that your bot would then iterate over, potentially locking the process.

DDOS Vulnerability Fix - Secure Facebook Webhook

---

lib/Slack_web_api.js

The users.setPresence method is currently missing from the Slack API. I'm not sure if there is a reason for this but I came across a need for it and figured I would submit a pull request (my first ever so be gentle).

Add users.setPresence to Slack API

---

readme-slack.md

A, uh, friend of mine, copied the url over when configuring and it unfortunately had the misspelled version of `receive`. Whoops.

Fix a couple typos for Slack

---

lib/CoreBot.js

Minor change - debug message: Show the status when the conversation is over. I need this for debugging an edge case in my bot an I suspect it might be useful to others.

Show status on conversation end debug message

---

lib/CoreBot.js

This fixes an error, if attachment is not defined.
/home/m/www/netwoRHk/node_modules/botkit/lib/CoreBot.js:441
if (attachments.length) {
^
TypeError: Cannot read property 'length' of undefined
at Conversation.replaceAttachmentTokens (/home/m/www/netwoRHk/node_modules/botkit/lib/CoreBot.js:441:28)
at Conversation.replaceAttachmentTokens (/home/m/www/netwoRHk/node_modules/botkit/lib/CoreBot.js:447:56)
at Conversation.cloneMessage (/home/m/www/netwoRHk/node_modules/botkit/lib/CoreBot.js:527:45)
at Conversation.tick (/home/m/www/netwoRHk/node_modules/botkit/lib/CoreBot.js:622:53)
at Task.tick (/home/m/www/netwoRHk/node_modules/botkit/lib/CoreBot.js:825:36)
at Object.Botkit.botkit.tick (/home/m/www/netwoRHk/node_modules/botkit/lib/CoreBot.js:1099:29)
at Timeout._onTimeout …

fix(CoreBot): guard array length access in replaceAttachmentTokens

---

readme.md

Simple documentation fix to account for extra botkit storage functions added.

Fix nine -> twelve in botkit storage docs

---

readme.md

#handling-the-end-of-conversation --> #handling-end-of-conversation

Fixed the link to #handling-the-end-of-conversation section

---

lib/Slack_web_api.js

Please add support for [channels.replies](https://api.slack.com/methods/channels.replies). As I understand it, this method can work with the default behaviour from `slack_api.callAPI`, at least it works fine for my app.

Add support for channels.replies method

---

.gitignore
lib/Facebook.js
readme-facebook.md

Yo guys,
Facebook allow us to configure the thread to help users link or unlink their Messenger identity with their identity in our business (a.k.a Account Linking).
By this PR i added the possibility to configuring account linking on the thread (add & remove)
[Read more](https://developers.facebook.com/docs/messenger-platform/thread-settings/account-linking)

Add Facebook thread setting account linking URL

---

readme.md

Hi,
I guess `changeTopic` is an old function and it has been changed to `gotoThread`
So this PR update it in the readme.md

Change `changeTopic` to `gotoThread` in readme

---

lib/SlackBot.js

The latest changes of Slack removed the concept of a bot from things like slash command. Botkit was still assuming that slack will send the `bot` key in the webhook payload which is not the case.
This is a simple fix that will remove the requirement for that information to be present for slash command, outgoing webhooks and interactive messages. The `handleEventsAPI` method will actually try to use that data so I still included it for that case but fail if we don't find it in the payload.
It was a blocker for us at message.io so we fixed and tested it in our own fork.
Should solve https://github.com/howdyai/botkit/issues/590#issuecomment-285186862

Fixes slash commands when using internal webserver

---

package.json
tests/Facebook.js

Putting in a PR with a simple test suite for the handleWebhookPayload mechanism of the Facebook bot

Add tests for handleWebhookPayload in Facebook bot flow

---

lib/SlackBot.js

I display the 'Add to slack' button on my website and submit the logged in user's id using the `state` parameter when clicked. However, it appears that parameter is currently not accessible in botkit. This fix works locally in my certain case, but as I'm new to botkit there may be issues with this implementation that I'm unaware of so I'd appreciate any feedback.
Thanks

Store state parameter from oauth against team

---

lib/Facebook.js

The point of these changes is necessity to receive/send information through small proxy.

Add ability to customize api url for Facebook

---

lib/CoreBot.js

I found it odd that your example for `conversation.ask()` shows a bot that expects responses of "YES, NO or DONE to quit", yet "done" isn't an expected utterance for "quit".
changes:
- Adds "done" to `botkit.utterances.quit`
- Adds "exit" to `botkit.utterances.quit`

adding "done" and "exit" as a utterances for "quit"

---

lib/Facebook.js
readme-facebook.md

Hello,
Messenger Codes can be scanned in Messenger to instantly link the user to your bot, no typing needed. They're great for sticking on fliers, ads, or anywhere in the real world where you want people to try your bot.
This PR add the ability to programmatically get your bot's Messenger Code.
Enjoy,

Add Messenger code API

---

readme-slack.md

This readme makes numerous references to "RTM" but never explains that this stands for Slack's Real Time Messaging API. This pull request adds that reference, including a link to Slack's Real Time Messaging API documentation.

provide definition of RTM

---

docs/readme-botframework.md
docs/readme-ciscospark.md

Some of the code examples didn't have any code highlighting, this PR fixes it.

Normalize Code Syntax Highlighting in /Docs

---

docs/readme-facebook.md
lib/CoreBot.js
lib/Facebook.js
lib/Tropo.js
tests/Facebook.js

Adds api support for the home_url in messenger 2.0
https://developers.facebook.com/docs/messenger-platform/messenger-profile/home-url/

Add support for new messenger 2.0 profile home_url

---

docs/readme-facebook.md
lib/Facebook.js

Yo,
Facebook just added (two days ago) the possibility to generate codes with ref parameters, So, the aim of this PR is to change on how we handle ```get_messenger_code``` to add support of parametric Codes.
Enjoy,

Add FaceBook parametric codes

---

lib/Facebook.js

This fix #795 
I removed the seconde deleteAPI from Facebook profile API section.

Remove the second delete api

---

lib/Facebook.js

When updating our Facebook bot to be conform to the latest Facebook changed, We have removed accidentally the customisation of Facebook API host (#567)
The aim of this PR is to bring it back.

Customize FacebookAPI link

---

docs/readme-slack.md

The code built into the Slack bot will call `controller.startTicking()` when calling `controller.startRTM()`; however, when using the Events API only `startTicking` will never get called and begin responding to conversations and threads.
There may be a better place to handle this via code, but a workaround is to manually call `startTicking` in this case.  The documentation could use an update to reflect this and prevent others from spending hours debugging why their conversations aren't working.

#737 Update Slack docs to include `startTicking` when using Events API

---

docs/readme-facebook.md
lib/Facebook.js

Hi,
Add the new target audience configuration to allow developers to customize bot's audience.
Enjoy,

Add FaceBook target audience

---

lib/Slack_web_api.js

- users.deletePhoto
- users.identity
- users.setPhoto
- users.profile.get
- users.profile.set
taken from: https://api.slack.com/methods

 Add missing user methods for slack api

---

docs/slack-events-api.md

Fixed `message.im` event name in the readme as per documentation here: https://api.slack.com/events/message.im

Fix: message.im event name

---

lib/Slack_web_api.js

Code Improvement:

---

lib/CoreBot.js

"that" is likely being declared on the global object, which may lead to leaks.

declare "that" in scope

---

lib/CoreBot.js

Trims whitespace from the events string passed to hears function in corebot. Passing a string separated by commas and spaces would previously trigger only for the first event. This PR allows comma plus space separated strings of event names to register the events for each.
Previously, given `'ambient, direct_message'`, it would split the string into an array that looked like this: `['ambient', ' direct_message']` notice the extra space in direct_message string. It would then register a listener to that event, with the space included, which could never be triggered by botkit.
I'm afraid this might be breaking, or introduce unintended results for people. However, it still will only trigger events they have explicitly stated, but developers might get surprised by their inert code running …

🐛 trim space characters in events string

---

__test__/lib/Botkit.test.js
__test__/lib/Slack_web_api.test.js
lib/CoreBot.js
lib/Slack_web_api.js

I think Node 4 requires the `use strict` directive to use `let`, `const`, and some other keywords. Under Node4 you will probably see this error:
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at ScriptTransformer._transformAndBuildScript (node_modules/jest-cli/node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
at emitTwo (events.js:87:13)
```
This PR adds the `use strict` directive to fix these types of errors.

adds use strict directive to test files that use ES6

---

lib/SlackBot.js

Not calling this error callback leads to a weird hard to debug state if you've changed your data store and forgot to re-auth the team for example.

Add missing error callback from team not found

---

lib/storage/simple_storage.js

fixed: 1st parameter of all 3 delete functions were mistaken

Fix- Delete functions parameter fixed in simple_storage.js 

---

lib/ConsoleBot.js

`bot.createConversation` is not implemented in Console Bot, but `bot.startConversation` is. PR adds `createConversation()` to console bot object.
Somebody ran into this on dev4slack testing an existing bot on the command line.

add bot.createConversation to ConsoleBot.js

---

docs/readme-facebook.md
examples/facebook_bot.js
lib/Facebook.js
npm-debug.log

Hello,
This PR add [Facebook attachment upload API](https://developers.facebook.com/docs/messenger-platform/send-api-reference/attachment-upload#message) to allow us uploading an attachment that we may later send out to many users, without having to repeatedly upload the same data each time it is sent.
:beer: in honour of @jonchurch :beer: 
Enjoy,

Add Facebook attachment upload api

---

docs/readme-slack.md

"Always appear online" is now an option when setting up events API within the slack dev admin panel.

[Slack Docs] remove Events API presence indicator caveat 

---

docs/readme-slack.md
lib/Slack_web_api.js
lib/Slackbot_worker.js

First pass at this for everyone hungry to jump on the new features! 
This adds two new functions to Botkit to make use of the new [`chat.postEphemeral`](https://api.slack.com/methods/chat.postEphemeral) Web API method.
Works just like bot.reply, takes a source message and clones the channel and user (user is required for this api method) and sends it. We also set `as_user` to true to show the messages are coming from the bot user (or whoevers token you're making calls with). This can be overridden by setting `user: false` on the outgoing message body, or using the second new method:
Works like bot.send, takes a botkit message with a channel and user (again, user is required for this method by slack) and sends a message, unprompted by the user.
~Currently there is shakey support of …

[Slack] 👻 Add Ephemeral Message Support

---

lib/Slack_web_api.js

This API method is not available to bot tokens, but if you override the 
> bot.api.files.sharedPublicURL({token: team.bot.app_token, file: fileId},....
it works just fine on my forked version.

Added files.sharedPublicURL to slack_web_api

---

docs/readme-twiliosms.md
lib/TwilioSMSBot.js

Hello Botkit team :wave:
This PR adds support for Twilio SMS outgoing media attachments (MMS) along with documentation on how use the feature.
--- 
To send media attachments, pass a `mediaUrl` property to any of Botkit's outgoing messages functions (`reply`, `say`, `ask`, etc.) with an optional `text` property for text that goes along with your attachment.
```js
/*
Sending an attachment
*/
bot.reply(message, {
text: 'Optional text to go with attachment',
mediaUrl: 'https://i.imgur.com/9n3qoKx.png'
})
```
> Note: your Twilio number as well as the recipient's phone must support MMS for media attachments to work
For more details on outgoing media attachments and a full list of accepted MIME types, go to [Twilio's docs on media attachment](https://www.twilio.com/docs/api/rest/accepted-mime-typ …

Add support for Twilio SMS outgoing media attachments (MMS)

---

examples/typescript_bot.ts
lib/Botkit.d.ts
package.json

Revised version of https://github.com/howdyai/botkit/pull/494.
I checked that this declaration file passed the examples on https://github.com/howdyai/botkit/tree/master/examples.

Typescript Declaration

---

lib/TwilioSMSBot.js

Hey there,
Just found a small typo in the Twillio SMS lib.  You can work around it if you set both `mediaUrl` and `medaUrl` like:
```convo.say({text: 'Here\'s your URL', mediaUrl: url, medaUrl: url})```
But that makes me sad.

Fix typo preventing Twilio Media Urls

---

changelog.md
docs/readme-slack.md
lib/SlackBot.js
lib/Slack_web_api.js
lib/Slackbot_worker.js
package.json

In reference to:
https://github.com/howdyai/botkit/issues/1064
* adds support for the new `bot.api.dialog.open` API call
* adds a new convenience method `bot.replyWithDialog()`
* emit `dialog_submission` event with `message.submission` field
* adds `bot.createDialog()` helper
* adds ability to respond with an error with `bot.dialogError()`
* adds `bot.dialogOk()` to respond with success
TODO:
* add need documentation in the docs/readme-slack.md file

add support for Slack dialogs

---

lib/Slackbot_worker.js

Tests for errors array in a safe way. I used `Object.prototype.toString.call` to be backwards compatible with pre-6 versions of Node. Otherwise Array.isArray would be the preferred way. 
Closes #1079.

tests if errors is an array in dialogError

---

lib/Botkit.d.ts

Documentation: https://api.slack.com/docs/formatting#message_formatting
Test Page: https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22title%22%3A%22Title%22%2C%22pretext%22%3A%22Pretext%20_supports_%20mrkdwn%22%2C%22text%22%3A%22Testing%20*right%20now!*%22%2C%22mrkdwn_in%22%3A%5B%22text%22%2C%22pretext%22%5D%7D%5D%7D

add mrkdwn_in to SlackAttachment in TypeScript definition

---

lib/Botkit.d.ts

A attachment may have one of the following types: "image", "audio", "video", "file" or "template", as defined here: https://developers.facebook.com/docs/messenger-platform/reference/send-api/#attachment

Include 'template' to possible FacebookAttachment types

---

docs/slack-events-api.md

Before it was:
_"Interactive messages" is Slack's fancy way of saying "buttons." In order to enable buttons, under Request URL, add https://my-bot-url/slack/receive, then click save."_
Now: 
_Interactive messages" is Slack's fancy way of saying "buttons." In order to enable buttons, click on the "Interactive Components" tab and under Request URL, add https://my-bot-url/slack/receive, then click save._

small addition, to make things clear

---

package.json

Every time when I run `npm update` I get this warning.
> npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
The only crypto method use by botkit is crypto.createHmac and it has never been provided by crypto package.
Crypto package provides implementation of md5 and sha1 functions: https://github.com/Gozala/crypto/tree/v0.0.3/

Removed crypto dependency

---

lib/Botkit.d.ts

Add `hears_regexp` function, and fix wrong type definition on `changeEars`.
I want to create a bot which doesn't react on the `#general` channel:
```typescript
const controller: botkit.SlackController = botkit.slackbot(<botkit.Configuration>{});
function messageFilter(patterns: string | string[] | RegExp | RegExp[], message: botkit.Message): boolean {
// hears default function + Check whether the channel of message is #general.
return message.channel != "#general" && controller.hears_regexp(patterns, message);
};
controller.hears(["hello", "hi"], "direct_message", messageFilter, function(bot: botkit.SlackBot, message: botkit.Message) {
bot.reply(message, "hello");
});
```

Add hears_regexp to TypeScript definition.

---

examples/twilio_sms_bot.js
lib/TwilioSMSBot.js

This is a fix for issue https://github.com/howdyai/botkit/issues/1107
Purpose: twilio signature validation feature needed for webhook endpoint in twilio-sms-bot
Changes: as suggested in https://www.twilio.com/docs/api/security

validate twilio signature for webhook endpoints in twilioSMSBot

---

lib/Sockets.js

Sockets.js no longer sets up webserver, that code was removed by https://github.com/howdyai/botkit/commit/04d27a1cab51c0dbe8fdea510ffdf6a1bfce944c#diff-e649c0cbc8744146309ee107c2a300feL250

[Sockets] Removed unnecessary require statements

---

lib/CoreBot.js

Most storage methods have no delete method,
but [simple_storage(files)](https://github.com/howdyai/botkit/blob/master/lib/storage/simple_storage.js#L59),  [couchdb](https://github.com/barlock/botkit-storage-couchdb/blob/master/lib/storage.js#L60) and [beepboop](https://github.com/BeepBoopHQ/botkit-storage-beepboop/blob/master/src/storage.js#L84) storage modules have it, so I am adding it to memory store.

Add delete method to in-memory store

---

lib/CoreBot.js

It is annoying, one warning on startup is enough.
```js
botkit.log('** No persistent storage method specified! Data may be lost when process shuts down.');
```
https://github.com/howdyai/botkit/blob/v0.6.6/lib/CoreBot.js#L1458
I am using botkit-middleware-watson in my projects, it passes each message to Watson Conversation and stores current state to botkit storage after receiving response from Conversation.
At first I used file storage (default option from starter-kit).
Then I started writing tests with testmybot and found that memory storage fits my needs better.
But getting `Warning: using temporary storage. Data will be lost when process restarts.` line after each passed message pollutes test output quite a lot.
When we got ready to deploy in production, we discussed things with our …

memory store: don't log warning after each save

---

lib/Slackbot_worker.js
package.json

Breaking changes in [3.0.0](https://github.com/websockets/ws/releases/tag/3.0.0) were:
```
Removed the upgradeReq property (#1099).
Removed unnecessary events (#1100).
Removed the flags argument from the 'message', 'ping', and 'pong'
events (#1101).
The permessage-deflate extension is now disabled by default on the server
(#1107).
```
Only flag argument change affects botkit, but flags argument was unused.

Upgrade ws library

---

lib/CoreBot.js

I don't know if this change fixes any real issue, but not calling a callback when it is provided is obviously wrong.

[CoreBot] Don't suppress errors

---

lib/Facebook.js

pass error object to the callbacks for failed send Api calls

---

lib/SlackBot.js

Slack provides a token to verify that requests are indeed coming from slack. 
I have put a optional test for this. If config has `clientVarificationToken` it will be tested against all the slash command and interactive requests. 
In addition to that when we set a new `ngrok` url in Slack, Slack does a ssl check and that breaks code. I have handled that too.

add Slack token verification

---

docs/readme-facebook.md
lib/Facebook.js

Hello,
Almost every Graph API call requires an access token. Malicious developers can steal access tokens and use them to send spam from your bot with malicious software on a person's computer or a man in the middle attack. 
To prevent that, Facebook recommend sending an app secret proof parameter to every API call. 
This PR add a new configuration attribute ```require_appsecret_proof``` to enable sending the sha256 proof each call Botkit makes.
````
var controller = Botkit.facebookbot({
debug: true,
log: true,
access_token: process.env.page_token,
verify_token: process.env.verify_token,
app_secret: process.env.app_secret,
require_appsecret_proof: true
});
````
Enjoy :v:

Securing FB Graph API Requests

---

docs/readme-facebook.md
examples/facebook_bot.js
lib/Facebook.js

Hello,
As of the release of Messenger Platform v2.2 including the messaging_type property in all message sends is become highly recommended.
Beginning May 7, 2018, this property will be required for all message sends !
For more information documentation is [here](https://developers.facebook.com/docs/messenger-platform/reference/send-api/)
Enjoy :sunglasses:

Include messaging_type property in all Botkit message sends

---

lib/Facebook.js

Hi,
This PR is about fixing the fb messages with tags request as documentation said, the request must be like that :
````
{
"recipient": { 
"id": "<PSID>"
},
"message":{
...
},
"tag": "SHIPPING_UPDATE"
}
````
Instead of that : 
````
{
"recipient": { 
"id": "<PSID>"
},
"message":{
...
"tag": "SHIPPING_UPDATE"
}
}    
````
Enjoy :flushed:

Properly format fb messages with tags request

---

docs/readme-facebook.md
lib/Facebook.js

Hello,
This PR add the new FB Broadcast API to send a message to many recipients.
Enjoy :alien:

Add FB Broadcast Messages API

---

docs/readme-facebook.md
examples/facebook_bot.js
lib/Facebook.js

Hello,
This PR add the new FB insights API to the awesome Botkit.
Fix #1126 
Enjoy

Add Facebook insights API

---

lib/Facebook.js

If the Facebook profile API returns the user's email address, which it does for Workplace integrations, the Botkit profile should include it.
This should have no impact on the current values and behaviour for page-associated bots.
Resolves #1192

Include user's email in profile if returned from facebook API

---

lib/SlackBot.js

This is a fix for issue https://github.com/howdyai/botkit/issues/601
Root cause of the Issue:
issue occurs because when we enable token verification for the slack webhook endpoint, verification middleware get's applied to all the endpoints (including "/login" and others) since middleware is mounted at the root .
Fix:
Changes in this PR ensure that verification middleware only get's applied to slack webhook endpoint (i.e. `/slack/receive`)

apply verification middleware only on the webhook endpoint

---

lib/Facebook.js

Hello,
While error in getting tags list, Botkit doesn't call cb function with the error. this PR allows ````tags.get_all```` to handle the cb function with ````err```` parameter, it also check if ````cb```` exists before calling it.
Enjoy,

Call FaceBook call back functions if error has occurred

---

lib/Botkit.d.ts

Last minute change in webchannel branch renamed SocketBot to WebBot in javascript code,
I implemented the same change in Typescript definition file.

[Typescript] Rename SocketBot to WebBot

---

lib/Teams.js

@peterswimm @benbrown fix for openUrl action of the hero cards, doesn't currently work but will when you use value over payload for the keyname.

should use value not payload as keyname

---

docs/readme-middlewares.md

Fix broken links to dashbot botkit middleware (Slack and Facebook) that leads to a 404.

Fix broken Dashbot links in middleware docs

---

docs/readme-facebook.md
lib/Facebook.js

Hello,
FB recently added the ````/request_thread_control```` endpoint that allows secondary receiver apps to request thread control from the primary receiver app, that's what i tried to introduce by this PR.
Enjoy

Add FB request thread control

---

lib/Facebook.js

There is a missing field, namely`locale` which is a part of the identity response object of `bot.getMessageUser`

Extend Facebook's user profile object with locale.

---

docs/readme-facebook.md
lib/Facebook.js
package-lock.json

Send broadcast function: added missing args(notification and tag)

---

lib/CiscoSparkbot.js

Botkit forced https, but Spark doesn't require it

Remove HTTPS governor

---

lib/Slackbot_worker.js

We recently hit an odd issue with Slack: Slack is sending us messages over RTM which are not valid JSON. In order to debug this and send a useful error report to the Slack platforms team, we needed the actual messages being received, to see if they're truncated, empty or something else. I've sent this PR because this change seems like it would be helpful to others, as well.
P.S. Unfortunately, I was unable to run the tests—when I tried, I got these errors:
```
FAIL  __test__/lib/Botkit.test.js
● exports bot interfaces
Cannot find module 'ltx' from 'JabberGroupManager.js'
at Resolver.resolveModule (node_modules/jest-cli/node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:179:17)
at Object.<anonymous> (lib/JabberGroupManager.js:6:61)
● exports bot interfaces
TypeError: Cannot …
```

Log bad JSON received by Slack if Slack sends us bad JSON.

---

lib/Facebook.js

Hi,
This PR about promisify Facebook messenger profile API to fix #1292 and properly catching error to fix #1299.
Enjoy,

Promisify Facebook messenger profile API

---

docs/readme-slack.md

I am currently implementing some interactive messages and dialogs on a Slack Bot, heavily relying on your's and Slack's documentation. While implementing a button that triggers a dialog I found that this example was not showing any buttons. After comparing it with Slack's message builder found that `fallback` is a required field.

Add missing `fallback` in example

---

lib/Facebook.js

FB require_delivery: Remove use of message.delivery.mids because not guaranteed

---

__test__/lib/Slackbot_worker.test.js
lib/Slackbot_worker.js

Added test file for `lib/Slackbot_worker` that did not exist at all, that tests just `startRTM`.
Closes #1334

call startRTM callback on websocket errors

---

lib/Botkit.d.ts

- Updating SlackAttachment type for interactive messages
- Updating Message type for interactive message handling
closes #1317

Updating typings for interactive messages

---

docs/readme-facebook.md
lib/Facebook.js

Hello,
This PR add the Thread Owner API that allows getting the app ID of the app the currently has thread control for a Page.
[Doc here](https://developers.facebook.com/docs/messenger-platform/handover-protocol/get-thread-owner)
Enjoy

Add FB Thread owner API

---

docs/readme-facebook.md
lib/Facebook.js

Hi, 
This PR adds FB scheduled broadcast management to handover API :
- ````cancel_scheduled_broadcast(...)````
- ````get_broadcast_status(...)````
[Doc here] (https://developers.facebook.com/docs/messenger-platform/send-messages/broadcast-messages/#scheduling)
Enjoy ✌️

Add FB scheduled broadcast

---

lib/Botkit.d.ts

I want to use `say()` without casting bot to `any`. 😃
Also fixes `BotFrameworkController.createWebhookEndpoints()` accepts `TwilioSMSBot` by mistake.

Add missing methods to d.ts

---

docs/readme-facebook.md
lib/Facebook.js

Hello 👋 
This PR adds Facebook payment settings to messenger profile API.
[Docs here](https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/payment-settings)
Enjoy

Add FB payment settings API

---

docs/readme-slack.md
lib/CoreBot.js
lib/SlackBot.js
package-lock.json

This is first cut. 
Biggest caveat in the current approach is control of webserver. HMAC signature needs raw request body. So far the only way to do with express is via a middleware. That needs to be added before usual `handleWebhookPayload`.
PS: You will have to add the following snippet just after you create `webserver` in your code.
```js
var webserver = express();
webserver.use(function(req, res, next) {
req.rawBody = '';
req.on('data', function(chunk) {
req.rawBody += chunk;
});
next();
});
```

Request Signing with Slack Signing Secret

---

lib/Botkit.d.ts

This pull request adds return types to the type definitions for the `TeamsAPI` interface.
Resolves #1420.

fix: add return types for TeamsAPI method type definitions

---

examples/google_hangouts_bot.js
lib/GoogleHangoutsBot.js

Hello,
This adds support for google hangouts interactive cards.
Enjoy

[Hangouts] Add interactive cards support

---

changelog.md
lib/CoreBot.js
lib/Studio.js
package.json

This pull request beings the process of removing Botkit Studio features from Botkit core.
In particular, this PR:
* Removes calls to Botkit Studio's metrics APIs
* Removes all metrics/stats features
* Removes the user id parameter from calls to Botkit Studio's content management APIs

Remove Botkit Studio metrics features

---

lib/SlackBot.js

As per https://api.slack.com/docs/verifying-requests-from-slack - "Compare the resulting signature to the header on the request. Note: for best practice, use an hmac compare function instead of directly comparing the signatures for equality."

use hmac compare instead of direct compare

---

bin/cli.js

How to use 'say' function is wrong.
When building an environment with docker etc, it is difficult to understand the error message in an environment where git is not installed.

Custom error message for cli

---

lib/Facebook.js
package-lock.json

This PR implements more promises into `lib/Facebook.js`, as requested in Issue #1520

Closes #1518: Allow Promises when on Facebook API calls

---

lib/GoogleHangoutsBot.js

Instead of setting `GOOGLE_APPLICATION_CREDENTIALS` with the path of the json google auth file, this PR allow to use `GOOGLE_APPLICATION_CREDENTIALS_DATA` that contains the actual json data. This idea come from [here](https://github.com/googleapis/google-auth-library-nodejs/blob/master/README.md#loading-credentials-from-environment-variables).
It will allow to use botkit as a hangout chat bot on Heroku like systems.
You need to start botkit like that:
```
$ GOOGLE_APPLICATION_CREDENTIALS_DATA='{
"type": "service_account",
"project_id": "your-project-id",
"private_key_id": "your-private-key-id",
"private_key": "your-private-key",
"client_email": "your-client-email",
"client_id": "your-client-id",
"auth_uri": "https://accounts.google.com/o/oauth2/auth",
"token_uri": …
```

hangouts chat: allow to consume auth data from env var instead of file

---

lib/Slack_web_api.js

PHP-style array argument is never valid in Slack API
fixes #1522

set useQuerystring to true in Slack API

---

lib/SlackBot.js

- We recently had an Enterprise Grid customer sign up. Somehow, we're receiving webhook events from teams that are part of their grid that haven't signed up yet and thus are not in our database. This has blown up our errors and now we're getting hundreds of emails a day.
- Please note that I originally changed these from simple return statements (that would eventually timeout) to 500 status codes. So I'm just doing what I should've done in the first place :)

Change 500 to 404 when team not found

---

lib/Slack_web_api.js

We recently got rate a limit error. An error message provides no information about  [`Retry-After`](https://api.slack.com/docs/rate-limits) time. This PR includes more response details when the rate limit error is hit.

slack api - extend error object with response details if rate limit is hit

---

lib/SlackBot.js

We tried to use new feature of  slack - `blocks` (in `chat.postMessage`) but botkit implementation does not support it. So we added `blocks`  to `format` middleware.

slack api - support of blocks

---

lib/CoreBot.js

- this benign change reduces mem usage by about 2MB when not using simple_storage
```
> botkit@0.7.2 test /Users/tonym/sources/botkit
> jest
PASS  test/Botkit.test.js
Botkit
✓ Should export bot interfaces (9ms)
PASS  test/facebook/Bot.test.js
FacebookBot
✓ adds 1 + 2 to equal 3 (8ms)
PASS  test/facebook/Handover_profile_api.test.js
Handover_profile_api
✓ Should not fail (4ms)
PASS  test/facebook/Tags_api.test.js
Tags_api
✓ Should not fail (1ms)
PASS  test/facebook/Broadcast_api.test.js
Broadcast_api
✓ Should not fail (2ms)
PASS  test/facebook/Insights_api.test.js
Insights_api
✓ Should not fail (1ms)
PASS  test/facebook/User_profile_api.test.js (6.653s)
User_profile_api
✓ Should not fail (10ms)
PASS  test/facebook/Attachment_upload_api.test.js (6.72s)
Attachment_upload_api
✓ Should not …
```

only require simple_storage when used

---

packages/botbuilder-facebook/.eslintrc.js
packages/botbuilder-facebook/.gitignore
packages/botbuilder-facebook/package-lock.json
packages/botbuilder-facebook/package.json
packages/botbuilder-facebook/src/botworker.ts
packages/botbuilder-facebook/src/facebook_adapter.ts
packages/botbuilder-facebook/src/facebook_api.ts
packages/botbuilder-facebook/src/facebook_event_middleware.ts
packages/botbuilder-facebook/src/index.ts
packages/botbuilder-facebook/tsconfig.json
packages/botkit/src/botworker.ts
packages/botkit/src/conversation.ts
packages/testbot/bot.js
packages/testbot/features/convo.js
packages/testbot/features/facebook_features.js
packages/testbot/features/hear_patterns.js
packages/testbot/features/z_fallback.js
packages/testbot/package.json

Fixes #1576 
To use, create an adapter like this and pass it into your Botkit constructor:
```
const adapter = new FacebookAdapter({
verify_token: process.env.FACEBOOK_VERIFY_TOKEN,
access_token: process.env.FACEBOOK_ACCESS_TOKEN,
app_secret: process.env.FACEBOOK_APP_SECRET,
})
// emit events based on the type of facebook event being received
adapter.use(new FacebookEventTypeMiddleware());
```
Still to do:

Port of Facebook to new adapter format

---

lib/Facebook.js

As of the release of Graph API v3.1 on July 26, 2018, the default permissions allowed for retrieval of user profile data are:
```
name,first_name,last_name,profile_pic
```
[Documentation is here.](https://developers.facebook.com/docs/messenger-platform/identity/user-profile/#fields)
To retrieve additional fields such as `locale`, `timezone`, and `gender` requires additional page permissions.
- Change o only retrieve the default fields from user profile
https://github.com/howdyai/botkit/issues/1589

Set correct Facebook profile default fields

---

packages/botkit/src/conversation.ts

Fixes `error TS1122: A tuple type element list cannot be empty.`

Fix type error of attachments field

---

packages/botkit/package-lock.json
packages/botkit/package.json

After upgrade to `4.0.0-prerelease-4` I got this error on `npm start`
```
Error: Cannot find module 'botframework-connector'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
at Function.Module._load (internal/modules/cjs/loader.js:508:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (/node_modules/botkit/lib/adapter.js:19:34)
```
Adding this dependency explicitly should fix it.

Added missing dependencies of botkit core

---

packages/botbuilder-adapter-slack/src/slack_dialog.ts

Changing option_list to an array of object.

fix(#1633): addSelect param types

---

packages/botbuilder-adapter-web/src/web_adapter.ts

Can be used to avoid sending notifications after disconnect.
Example: 
```typescript
if (bot.controller.adapter.isConnected(message.user)) {
const newBot = await bot.controller.spawn({});
await newBot.changeContext(message.reference);
await newBot.reply(message, { text: 'You were inactive for too long and your session timed out.', action: 'exit' });
}
```

WebAdapter: Add isConnected method

---

packages/botbuilder-adapter-slack/src/slack_adapter.ts

On Slack adapter, `redirectUri` is not send to Slack via `getInstallLink()`. Therefore Slack is redirecting to a wrong url during installation, hitting the wrong endpoint and breaking installation.
If you use the Slack adapter with a `redirectUri` param before this fix, you cannot trigger OAuth with Botkit `getInstallLink()`.

[Slack] Add redirectUri in getInstallLink()

---

packages/botbuilder-adapter-slack/src/botworker.ts

- Replace `src.channnel` with `src.channel`  in [packages/botbuilder-adapter-slack/src/botworker.ts](https://github.com/howdyai/botkit/blob/master/packages/botbuilder-adapter-slack/src/botworker.ts#L244)

[adapter-slack] Fix typo in 'src.channnel' in 'replyInteractive'

---

packages/botbuilder-adapter-web/src/web_adapter.ts

I did some testing over websockets and forcibly closed websocket connection without waiting for all response messages.
It produced 3 types of errors in bot's output:
```
Could not send message, no open websocket found
```
```
Error: WebSocket is not open: readyState 2 (CLOSING)
at WebSocket.send (.../node_modules/ws/lib/websocket.js:329:19)
at WebAdapter.<anonymous> (.../node_modules/botbuilder-adapter-web/lib/web_adapter.js:183:32)
at Generator.next (<anonymous>)
at .../node_modules/botbuilder-adapter-web/lib/web_adapter.js:14:71
at new Promise (<anonymous>)
at __awaiter (.../node_modules/botbuilder-adapter-web/lib/web_adapter.js:10:12)
at WebAdapter.sendActivities (.../node_modules/botbuilder-adapter-web/lib/web_adapter.js:172:16)
at emit …
```

fix: WebAdapter only sends message if websocket is OPEN

---

packages/botkit/src/core.ts

According to documentation at https://github.com/howdyai/botkit/blob/master/packages/docs/core.md#sending-alerts-and-scheduled-messages, config parameter of spawn() is optional.
However I got an error when compiling my bot:
```
src/actions.ts:117:42 - error TS2554: Expected 1 arguments, but got 0.
117                     const newBot = await bot.controller.spawn();
~~~~~~~~~~~~~~~~~~~~~~
node_modules/botkit/lib/core.d.ts:502:11
502     spawn(config: any): Promise<BotWorker>;
~~~~~~~~~~~
An argument for 'config' was not provided.
```

Fix signature of spawn method

---

packages/botbuilder-adapter-facebook/src/facebook_adapter.ts
packages/botbuilder-adapter-hangouts/src/hangouts_adapter.ts
packages/botbuilder-adapter-slack/src/slack_adapter.ts
packages/botbuilder-adapter-twilio-sms/src/twilio_adapter.ts
packages/botbuilder-adapter-web/src/web_adapter.ts
packages/botkit/src/core.ts

Because they don't do anything

Remove useless catch-throw blocks

---

packages/botbuilder-adapter-web/src/web_adapter.ts

Direct access to WebSocket connection can be useful, but there were no means to access connection of specific user.
What I actually wanted to do:
I got a feature request to log user's ip and user agent, but they are only available in `on connection` event handler as a second parameter, so I implemented event handler and made it assign custom properties to WebSocket objects.
```js
if (controller.adapter instanceof WebAdapter) {
controller.ready(() => {
const wsServer: WebSocket.Server = controller.adapter.wss;
wsServer.on('connection', (ws, req) => {
ws.ip = req.connection.remoteAddress;
ws.userAgent = req.headers['user-agent'];
});
});
}
```
Then I can access them in my bot's code like this:
```js
if (bot.controller.adapter instanceof WebAdapter) {
const connection = …
```

WebAdapter: add getConnection method

---

packages/generator-botkit/generators/app/templates/features/sample_echo.js

After updating to 1.0.1 the samples created with the yeoman generator no longer work in a direct space.

Update sample_echo to respond to direct messages

---

packages/botkit/src/core.ts

Receive middleware is not running when it match with a hear() trigger.
I moved hear check into receive middleware
#1702

Fix middleware pipeline

---

packages/botbuilder-adapter-slack/src/slack_adapter.ts

Convert block_actions to `ActivityTypes.Message` just like user messages, so block_actions like button presses can be used to respond to BotkitConversation dialogs. Fixes howdyai/botkit/issues/1711.

change block_actions to Message events fixes howdyai/botkit/issues/1711

---

packages/generator-botkit/generators/app/templates/bot.js

Botkit-cms-plugin expects uri instead of cms_uri

Change cms_uri to uri

---

packages/botkit-plugin-cms/src/cms.ts

Now you can write cms_uri with or whitout last /

Create uri with URL object

---

packages/botbuilder-adapter-slack/src/slack_dialog.ts

Adding broader types for optionsList.

fix(dialog): broader types for options list

---

packages/botbuilder-adapter-webex/src/webex_adapter.ts

1. the webex message api also supports to send messages with attachement, at this time, the request [`content-type` is `multipart/form-data`](https://developer.webex.com/docs/api/basics/message-attachments), so here the null value will break the [FormData used by request](https://github.com/form-data/form-data/blob/master/lib/form_data.js#L226).
2. `roomId`, `toPersonId` and `toPersonEmail` should be provided only one, otherwise, `BadRequest: Message destination could not be determined. Provide only one destination in the roomId, toPersonEmail, or toPersonId field`

Fix webex adapter to support FormData

---

packages/botkit/src/conversation.ts

Convo.ask() without storage key throws error, It forces to add a empty object or caracter

Change conversations key to optional

---

packages/docs/core.md

The example code for the form of a plugin with automatically bound middlewares was incorrect. The actual key that usePlugin()'s source code refers to is `middlewares`, not `middleware`. Without this fix in the example code, middlewares are not automatically bound. With this fix, they are bound as expected.

Fix typo breaking plugin middleware example code

---

packages/botbuilder-adapter-webex/src/webex_adapter.ts

Fixes the issue in #1759 so that the attachments field is added to the message sent to webex teams in order to enable the sending of adaptive cards.

Add attachments to webex teams adapter to support adaptive cards fixes #1759

---

packages/botbuilder-adapter-webex/package-lock.json
packages/botbuilder-adapter-webex/package.json
packages/botbuilder-adapter-webex/readme.md
packages/botbuilder-adapter-webex/src/botworker.ts
packages/botbuilder-adapter-webex/src/webex_adapter.ts
packages/docs/index.json
packages/docs/platforms/webex.md
packages/docs/reference/webex.md

Cisco Spark is rebranded to Webex, so that [ciscospark package is deprecated](https://www.npmjs.com/package/ciscospark), and following the [official guide](https://github.com/webex/webex-js-sdk/blob/master/UPGRADING.md) to upgrade to Webex.

Upgrade from Cisco Spark to Webex

---

packages/botbuilder-adapter-facebook/src/index.ts

In botbuilder-adapter-facebook, add facebook_api in index.ts to export it.
The linked issue is https://github.com/howdyai/botkit/issues/1762
After this fix, the `const { FacebookAPI } = require('botbuilder-adapter-facebook');` will work according to the document https://botkit.ai/docs/v4/reference/facebook.html#FacebookAPI

export facebook_api in index.ts

---

packages/botbuilder-adapter-facebook/src/facebook_adapter.ts

Fix a typo that causes an error during handover of thread from bot to messenger inbox. 
This fixes https://github.com/howdyai/botkit/issues/1694

fix error when initiating handover protocol

---

packages/botbuilder-adapter-slack/package.json
packages/botbuilder-adapter-slack/src/botworker.ts
packages/botbuilder-adapter-slack/src/messagetype_middleware.ts
packages/botbuilder-adapter-slack/src/slack_adapter.ts
packages/testbot/features/slack_modals.js

This PR adds support for [Slack's new modal APIS and events described here](https://api.slack.com/block-kit/surfaces/modals)
Changes include:
* Update dependency to latest version of @slack/web-api
* Add some new sample code to the testbot
* allow events without channels -- because new modal events do not include channel data. (This means bot.reply will not work with these events, amongst other caveats)
In addition, this will fix the behavior that caused all "block_actions" and "interactive_message" events to become "message" events.  These events will retain their native event type, but will still be passed into active dialogs (so a button click can be passed to a convo.ask)

Add support for Slack's new modals APIs and events

---

packages/botbuilder-adapter-slack/src/slack_adapter.ts

This change extends the existing 'Slack button event as Message' pattern to all Block Action events. This change includes 'select' events from static, external, overflow, user, conversation, and channel selections, as well as date picker selections.
This update is required to use Slack select and date picker Block elements in Botkit Conversations.

Add missing Block Actions to Botkit Conversations

---

packages/botbuilder-adapter-slack/src/slack_adapter.ts

When the Slack adapter receives an invalid signature header, it sets the status
code of the response to 401 but does not end the response.
This causes requests to hang that do not have a valid signature. This commit
therefore fixes the issue

End invalid Slack signature response.

---

packages/botkit/src/core.ts

A relatively small change that showed up when I was using typescript for my features in the demo bot.

Support .ts (or parameterized) file extensions for loadModules

---

packages/botkit/package.json
packages/botkit/src/index.ts
packages/botkit/src/testClient.ts
packages/botkit/tests/Core.tests.js
packages/botkit/tests/Dialog.tests.js

Hello! Our team is starting to love the library you are developing. Since we are starting to consider writing tests to make sure our botkit bots are behaving as expected.
Since we could not find a specific way to test the library, I went ahead and searched around the web for a way to test botbuilder bots. Microsoft seems to provide a way to do it: https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-testing/src/dialogTestClient.ts
So I went ahead and brought that code back into Botkit's code base and adapted it to take a Botkit instance and a thread name to test. I have provided an example test file showing how to use the test client in the PR.
This will be immensely useful for both our team and the whole botkit community.

Botkit dialog test client

---

packages/docs/reference/core.md

Fixed a typo in the example for `ask()` - https://botkit.ai/docs/v4/reference/core.html#ask
```js
{
pattern: 'no',
type: 'string',
handler: async(response, convo, bot) => {
return await convo.gotoThread('no_taco');
}
},s
{
```

Fixed a typo

---

packages/docs/core.md

Added the missing 'controller' param to the BotkitCoversation constructor in the taco dialog example
In constant: onboarding

Added missing 'controller' param

---

packages/botbuilder-adapter-facebook/CHANGELOG.md
packages/botbuilder-adapter-facebook/package.json
packages/botbuilder-adapter-facebook/src/facebook_adapter.ts
packages/testbot/features/facebook_features.js

This pull request corrects the Facebook adapter's treatment of `sender_action` messages.
The change removes the `message` field from the outgoing payload when sender_action is present, as this causes Facebook to reject the message.

Fix Facebook typing indicator

---

packages/docs/conversations.md
packages/docs/index.md

Found 3 typos in the docs. This fixes them.

fix a few documentation typos

---

packages/botbuilder-adapter-slack/src/slack_adapter.ts

The `redirectUri` property of `SlackAdapterOptions` is only relevant for apps that uses OAuth. It is treated as optional by the code and the type definitions should reflect that.

Make redirectUri optional in type definition

---

packages/botkit/src/core.ts

Now botkit can handle both CJS `module.exports` and ESM `export default` syntax.
Previously only this was supported:
```js
module.exports = function(controller) {
controller.hears('sample', 'message', async (bot, message) => {
await bot.reply(message, 'I heard a sample message.');
});
}
```
Now you can also, optionally, use:
```js
export default (controller) => {
// ...
}
```

Support ES6 syntax for botkit features

---

.gitignore
packages/generator-botkit/CHANGELOG.md
packages/generator-botkit/generators/botframework/templates/.env
packages/generator-botkit/generators/facebook/templates/.env
packages/generator-botkit/generators/hangouts/templates/.env
packages/generator-botkit/generators/slack/templates/.env
packages/generator-botkit/generators/twilio-sms/templates/.env
packages/generator-botkit/generators/web/templates/.env
packages/generator-botkit/generators/webex/templates/.env
packages/generator-botkit/package.json

Somehow the .env templates never got included in the repo, and as a result created an invalid version.

Fix generator by replacing missing .env files

---

packages/botbuilder-adapter-slack/readme.md

New slack apps will use oauth v2 by default, we can explain the discrepancy to help devs get up and running faster.

add example response for oauth v2

---

packages/botbuilder-adapter-webex/src/webex_adapter.ts

This commit removes sending `files` key with empty string value when
there are no files while sending a message. `files` key with empty string is causing API to fail
with below `BadRequest: "Unable to retrieve content."`. I have validated
that by sending request to webex api from webex developer console.
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

(Webex) Remove `files` key with empty string value

---

packages/botbuilder-adapter-slack/package.json
packages/botbuilder-adapter-slack/src/botworker.ts
packages/botkit/package.json
packages/botkit/src/botworker.ts
packages/botkit/src/core.ts

Fixes #1937 
This is a fix to the change to how the adapter is referenced inside the botworker introduced in 4.8.
This change introduced a bug pertaining to spawning proactive slack bots.

Fix location of adapter in bot worker

---

packages/botkit/src/core.ts

Fixes .. controller.spawn() throws UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'context' of undefined . Fix for [BUG#1945](https://github.com/howdyai/botkit/issues/1945)
Sorry for the confusion on the last pull request. By mistake, I used wrong email address for commit. I had close the pull request and remove the fork. I incorporated all the changes you suggested in this one.

Update core.ts- Fix for [Bug#1945]

---

packages/botkit/src/conversation.ts

See [BotkitConversation.makeOutgoing](https://github.com/howdyai/botkit/blob/master/packages/botkit/src/conversation.ts#L795-L802) method. 
The `text` variable must be a string, as it is fed into the mustache renderer [here](https://github.com/howdyai/botkit/blob/master/packages/botkit/src/conversation.ts#L867). So the template function must always return a string, or the function will crash later on.
Therefore, the type definition must reflect that. I am getting TypeScript error when returning a string, if I can it to an array, botkit breaks. 😞

Fix dynamic text field type definition

---

packages/botbuilder-adapter-slack/src/slack_adapter.ts

Fixes issue #1943 
By removing this IF statement: 
**New generation bots** will be able to make use of `icon_url`, `icon_emoji` and `username` fields on the `reply` object without having Botkit forcing a deprecated field `as_user` set to false.
For **classic bots**, developers would still be able to add the `as_user` field manually as stated by the [Slack documentation](https://api.slack.com/methods/chat.postMessage#arg_as_user)
_(I'm not sure if I should make a PR to master or other branch, please advice)_

Removes enforcement of "as_user" field. Fixes #1943

---

packages/botkit/src/conversation.ts

You can get an undefined result at this point, since `runStep` can be called with an empty result. I don't believe it is assumed that an action handler is called always after the previous step generated a result
Until this is fixed, what would be an alternative?

Result is not necessarily defined here

---

packages/botbuilder-adapter-slack/src/slack_adapter.ts

Parity: https://github.com/microsoft/botbuilder-dotnet/pull/5393
When the user presses a button in slack, the one sending the payload to the bot is the user not the bot.
- Swapped the priority of the id to pick to populate activity.from.id

Slack Adapter - Prioritize User.id as From.Id

---

build/botkit-ci.yml
build/botkit-daily.yml

This is not relevant to Botkit and adds time to the builds.

Suppress Codesign Validation Injection

---

packages/botbuilder-adapter-webex/src/webex_adapter.ts

Currently, there is a bug that prevents dialogs to function properly in threads (webex adapter). This PR adds the missing parentId to the conversationID, so bottkit can recover the conversation and continue with the dialog
Example (this dialog can only happen after applying this PR, otherwise it stops at the first question):
Code for the example:
```
const MY_DIALOG_ID = 'my-dialog-name-constant';
const convo = new BotkitConversation(MY_DIALOG_ID, controller);
convo.say('Howdy!');
convo.ask('What is your name?', async(response, convo, bot) => {
console.log(`user name is ${ response }`);
}, 'name');
convo.addAction('favorite_color');
convo.addMessage('Awesome {{vars.name}}!', 'favorite_color');
convo.addQuestion('Now, what is your favorite color?', async(response, convo, bot) => { …
```

Webex adapter: Allow dialogs in threads
