howdyai/botkit

readme.md
'phrases' instead of 'phrasess'
=> Fix typo in README.md

examples/slackbutton_incomingwebhooks.js
=> Refactoring example code

lib/CoreBot.js
Let's be honest, this is about as small a PR as could possibly exist, but I use `yep` a lot, as do lots of people. (Maybe it's a British thing?)
=> Add 'yep' to yes utterances

lib/mongo_storage.js
since this uses [`monk`](https://github.com/Automattic/monk), there are some known bugs that are commonly encountered if the node version is 4 or above.
Notably: 
https://github.com/Automattic/monk/issues/91
https://github.com/Automattic/monk/issues/114
I chose Monk for its simplicity, though Mongoose is probably the safer bet if people want to use newer node versions (i'm using 0.12 for this currently).
Just an FYI!
=> added mongo storage client

examples/demo_bot.js, lib/CoreBot.js, readme.md
logging is now disabled by default, similar to how debug works
=> Made logging to console optional, also fixed a small typo

examples/demo_bot.js, lib/CoreBot.js, readme.md
Also fixes a small typo in ```demo_bot.js```.
Includes all of PR #45.
=> Makes logging optional

package.json
There were some errors while installing on node 4 and 5.
I update the dependencies and problem gone.
This site could help to be up-to-date. [https://www.bithound.io]()
=> Package dependencies updated.

.gitignore, lib/Slackbot_worker.js, package.json, test/Slack_web_api-test.js
- adds tape to start testing out the api and harden the code
- adds tap-spec for nice reporting
- fixes a bug on closeRTM for clean exit
=> adds tests and a fix for clean exit

lib/SlackBot.js
Addresses this issue https://github.com/howdyai/botkit/issues/27
=> added option to pass redirect_uri

.editorconfig, .jscsrc, CONTRIBUTING.md, bot.js, lib/Slackbot_worker.js, readme.md
It is really hard to both contribute and read the code clearly. Therefore, I've added editorconfig and linter files.
- Editorconfig helps new contributors with the tab character and changes it with spaces. 4 for all files, 2 for json files. It helps indentation in general.
- Modern text editors all have linter plugins for JavaScript including Atom, Webstorm etc. On top of Google's linter rules, I've made some adjustments to create a more unified code.
Hope you all like it.
=> Added linter & editorconfig

lib/CoreBot.js, lib/SlackBot.js, lib/Slackbot_worker.js, lib/console_logger.js, package.json, readme.md, test/Slack_web_api-test.js
To ensure that contributors run `jscs`, I've added `jscs` to package devDependencies and added a `"pretest"` script to run `jscs` according to the `.jscsrc` before running the unit tests.
=> Add jscs to scripts

lib/Slackbot_worker.js
@benbrown didn't mean to introduce these in the first place but here's some fixes to get the linter passing in slackbot worker
=> fix reply with typing linter errors

lib/CoreBot.js
running slackbutton_bot.js would crash on startup because events were coming in as an array already.
=> fix issue where events would come in as an array

.jscsrc, lib/CoreBot.js, lib/SlackBot.js, lib/Slack_web_api.js, lib/Slackbot_worker.js
Added a required space after commas into the jscsrc and updated files to meet the new conditions.
Requested here https://github.com/howdyai/botkit/pull/88#issuecomment-171300650
Let me know if I misunderstood the request, this touched more lines than I was expecting it to.
=> add requireSpaceAfterComma to jscsrc

examples/slackbutton_bot.js
Helps users by including the description of the example, as well as the basic instructions to use the example. Namely the `clientId=<my client id> clientSecret=<my client secret> port=3000 node bot.js` command.
=> Add file header to slackbutton_bot.js example

package.json
=> Add mocha as dev dependency

readme.md
=> Provide link in the readme, to a demo Express+Botkit app

examples/slackbutton_bot.js
You need to make sure that your Redirect URI include the /oauth to get the proper Oauth working.
I added the info in the comments in the header
=> Update setup info in slackbutton_bot.js

bot.js, lib/CoreBot.js, lib/Slackbot_worker.js, readme.md
Enable developer to change pattern matching function at a global level using controller.changeEars()
Strip @mentions from beginning of messages that are part of a conversation
Add additional .ask examples in bot.js
=> Use the same global pattern matching function inside convo.ask as is used at controller.hears

readme.md
"These message events can be handled <strike>using</strike> by attaching an event handler to the main controller object."  
In **readme.md > Developing with Botkit > Receiving Messages**
=> Fix Typo: "handled using by" -> "handled by"

readme.md
Changes "Botkit designed" to read "Botkit is designed".
Resolves issue #186
=> Fix typo in read me

readme.md
Also make it known that you must pass a text property to all message objects, even if it's only empty string
=> Add domentation for startPrivateConversation()

facebook_bot.js
no issue
- :robot_face: isn't supported on Messenger it seems.
=> Correct robot face emoji on Messenger.

examples/slackbutton_bot_interactivemsg.js
Just a minimal change to avoid confusion for people trying to run this example.
=> Adjust the example command-line call to use the new filename.

slack_bot.js
Sentence structure: missing word added
=> Sentence structure: missing word added

Dockerfile
A Dockerfile if you are interested in including it with this project.
This allows a user to easily setup and test/run this project using docker.
How a user could use this dockerfile (without docker hub):
```
git clone https://github.com/howdyai/botkit.git
docker build --tag botkit botkit/
Foreground:
docker run -it --rm --name botkit botkit sh -c 'token=<slack token> node slack_bot.js'
Background:
docker run -d --name botkit botkit sh -c 'token=<slack token> node slack_bot.js'
```
Users could easily specify their own js file from their host with something like:
```
docker run -d --volume=/home/foo/slack_bot.js:/app/slack_bot.js --name botkit botkit sh -c 'token=<slack token> node slack_bot.js'
```
My suggestion would be to setup an account on docker hub also so that you can leverage it to …
=> Basic Dockerfile to setup botkit

lib/Facebook.js
This adds the ability both send and receive quick_reply payloads.
=> Add support for Quick Reply as per Messenger v1.1 API

readme-slack.md
`method` should _probably_ be `methods`.
=> Fix small typo

readme.md
Readme on the multi-stage conversation example had a typo
=> fixed a typo with the documentation

readme-slack.md
=> Require correct module

botframework_bot.js, readme-botframework.md
I was passing the App ID & Password to the controllers constructor and should have been passing it into spawn().
=> App ID & Password should be passed to spawn() 

readme.md
Typo : readme-middlewares.md --> readme-middleware.md :bowtie:
=> Typo in readme.md

lib/Facebook.js
=> Re #552 - add support for referral param via postbacks (Facebook)

lib/Facebook.js, lib/SlackBot.js
hi,
I've fixed the path to the ExpressJS static directory with the directory where the process has been executed (not directory of the node package).
Cheers
=> static content directory

lib/CoreBot.js, lib/Studio.js, slack_bot.js
Add support for raw quick replies in Botkit Studio API response
Add a version() function that identifies the version of Botkit being used
=> Add version function to controller, adjust quick replies in Botkit Studio

lib/CoreBot.js, readme-middlewares.md
Hello Guys,
The aim of this PR is to integrate Recast.ai Botkit middleware.
Enjoy
=> Integrate Recast.ai to Botkit

readme.md
=> Fixing typo in a conversation example

readme.md
Unspecified programming language in code fences fixed
=> Fixing Readme.md

readme.md
I had to do google to figure out out to set timeout for a conversation. I see frustration in issue section not being documenting this. We have such useful method. So, I documented in front page.
=> conv.setTimeout(timeout) method documented.

lib/CoreBot.js
I got burned trying to debug #683 because the err was ignored and never logged. Added logging for it to save some poor future soul.
=> Added error logging for say and spawn.run

facebook_bot.js, lib/Facebook.js, readme-facebook.md
Hi,
Review the merging of PRs #573, #690 and #689 on the branch v0.5.2
=> Review the merge of 573, 690 and 689

facebook_bot.js, lib/Facebook.js, readme-facebook.md
Yo guys,
Facebook added Messenger Profile API for accessing our bot's properties, replaces the Thread Settings API. 
in this PR i migrate to the new API (Messenger Profile) while keeping the thread setting also available to not makes Botkit break changes.
Enjoy,
=> Messenger Profile API

examples/convo_bot.js
This example is not working with this change it works perfect
=> added direct_message to the array of events

examples/sentiment_analysis.js
When you imported files, my github authorship was lost.
=> Credit where credit is due

docs/readme.md
a couple of little typos in the docs here :)
=> fixed typos in convo.say() and convo.ask() references

lib/CoreBot.js, tests/Slack_web_api.js
reads current package version in a bundler-detectable way.
=> #774 expose package version to bundle

lib/Studio.js
* Ability to receive pre-defined variable values as part of the script payload
* Ability to receive platform specific fields (for Cisco Spark in particular)
=> New features for Botkit Studio

docs/readme.md
=> Correct url for Cisco Spark

lib/CiscoSparkbot.js
Respond to the Incoming Cisco Spark web hook with a 200 ok.
=> Respond with a 200 ok

lib/Botkit.js, lib/TwilioSMSBot.js, readme-twiliosms.md, twilio_sms_bot.js
Howdy, Botkit team! :wave:
I wrote this Botkit SMS implementation and [published it on `npm`](https://www.npmjs.com/package/botkit-sms) a while ago but never managed to submit a PR to include it in the main Botkit project. 
I modified it to match the project's source code style (checked using `jscs`), included it in `botkit`'s main export, and added an example bot.
Of course, this is a working draft. If you have any feedback, let me know :eyes:
This PR enables Botkit users to build SMS bots using [Twilio's Programmable SMS API](https://www.twilio.com/sms). This submission is for preliminary code review.
Similar to the Facebook Messenger implementation, Twilio Programmable SMS API sends webhooks to an arbitrary URI when SMS' are received. 
This implementation consists of mounting `express` …
=> Add support for SMS via Twilio Programmable SMS API (work in progress)

lib/CiscoSparkbot.js
This adjusts the way startPrivateConversationWithPersonId works to actually load the user's info, then pass it into startPrivateConversation with the expected email parameter.
=> Fix issue #864

lib/Sockets.js
Copied from Facebook [replyWithTyping ](https://github.com/howdyai/botkit/blob/master/lib/Facebook.js#L173-L194) function.
#872
=> [Sockets] send calculates typing length

lib/Sockets.js
Hello is the only message without user id and it can cause issues 
Related to #872
=> [Sockets] Assign uid to hello message

lib/Botkit.d.ts
=> TypeScript Definition: Fix SlackController type

lib/Studio.js
Botkit Studio will soon have the capability of defining custom fields on any message object. This adds support for these new fields in the Studio library.
=> Add ability to specify custom fields in the message object

lib/Sockets.js
It is a responsibility of the client side code to generate guid.
Fixes https://github.com/howdyai/botkit-starter-web/issues/10
Comes in pair with https://github.com/howdyai/botkit-starter-web/pull/11
=> [Sockets] dont set guid

docs/readme-facebook.md, lib/Facebook.js
Hello,
This PR fixe the issue #1090.
Enjoy
=> Allow disabling a customized build in nlp

lib/Botkit.d.ts
It is used by reply method in https://github.com/howdyai/botkit/blob/dev/webchannel/lib/Sockets.js#L225
=> [Sockets] Added replyWithTyping option to Typescript definition

docs/readme-middlewares.md
create for developers to view code. In connection between botkit and facebookapi
=> add botkit-middleware-facebookuser

lib/Facebook.js
fix for #852 bug
Code just set `deliveryMids` to value or `message.delivery.mids` or `[]`
=> Bug/#852 fixes an error when message.delivery.mids undefined

docs/readme-facebook.md, lib/Facebook.js
fix for issue #1212
check api_response.mid and api_response.message_id for a value to match mid
* `message_id` is currently be returned by facebook
* `mid` might have been returned before; leaving it is case it changes back
=> #1212 check api_response mid or message_id

lib/Teams.js
Fix for https://github.com/howdyai/botkit/issues/1222
=> Fixed MS Teams findConversation api typo error 

lib/Botkit.d.ts
=> Add updateResponse callback to replyAndUpdate type

lib/JabberBot.js, lib/JabberGroupManager.js, package.json
remove the dependency for Python in Cisco Jabber.
=> remove the dependency for Python 

lib/Slack_web_api.js
=> Modify duplicated `users.identity` to be `users.lookupByEmail`

lib/SlackBot.js
=> returning 500 status code under error conditions

changelog.md, lib/BotFramework.js, lib/CiscoSparkbot.js, lib/CoreBot.js, lib/Facebook.js, lib/Slack_web_api.js, lib/Slackbot_worker.js, lib/Studio.js, lib/Web.js, package.json
* Fix bugs and refactor handling of message actions, particularly as they relate to Botkit Studio scripts
* Adjust mechanism used to construct facebook quick reply payload in order to support future formats. [PR #1301](https://github.com/howdyai/botkit/pull/1301)
* Promisify Facebook Messenger profile API. [PR #1300](https://github.com/howdyai/botkit/pull/1300)
* Lower the log priority from 'log' to 'debug' for several messages in Botkit Core and Botkit Slack.
=> 0.6.13 - bug fixes

docs/readme-ciscospark.md
The array to obtain the Attached files is message.data.files not message.original_message.files
=> Correction of array name to receive attachments

changelog.md
FIx a small typo in my name : oaudie > ouadie
=> Fix typo in changelog.md

lib/Slack_web_api.js
Back with another one, 2 years later.
New method came out in April 2018.
=> Add new users.conversations web api endpoint

lib/Botkit.d.ts
=> Add `collectResponse` to CoreBot's public types

lib/CoreBot.js, lib/Utils.js, lib/utterances.json
##What's there in this PR?
* Delegate the utterances object creation to a `Utils` file which imports the `utterances.json` and creates the RegEx Object for each key.
* Since it is an internal optimization, no changes in documentation required.
=> Externalize the utterances object

lib/Facebook.js
Just deleted duplicated conditional. #1463
=> Remove duplicate line in facebook controller

lib/Web.js
Just return WebSocket Server to use it outside. #1475
=> Expose wss

lib/CoreBot.js
Fixes #1480 and #1291 and replaces #1481
=> Fix issue where  property of a message was ignored on first message in thread

lib/Web.js
This is a pull request for this related issue #1450, Adding a try/catch to server message parsing related to issue #1450
=> Add try/catch to server message parsing

lib/Botkit.d.ts
=> adding clientVerificationToken to SlackConfiguration

examples/facebook_bot.js, lib/Facebook.js
Hello everybody 👋 
This adds Facebook Personas API to Botkit.
FB Documentation > [here](https://developers.facebook.com/docs/messenger-platform/send-messages/personas/)
Enjoy
=> Add Facebook Personas API

.github/issue_template.md
Hello,
This adds an issue template file that project contributors will automatically see the template's contents in the issue body.
=> Create issue template file

lib/Slack_web_api.js
the pull request is reaction to suggestion https://github.com/howdyai/botkit/pull/1594#issuecomment-466255362
=> slack api - extend support of blocks

lib/Slack_web_api.js
Slack recently released new functionality!
https://api.slack.com/messaging/scheduling
=> Added Slack chat.scheduleMessage to web api

lib/Botkit.d.ts
It closes issue https://github.com/howdyai/botkit/issues/1620
=> Add successful method to Converstaion definition

lib/Slackbot_worker.js
To support: https://api.slack.com/dialogs#state
=> Add dialog state to Slackbot worker createDialog

packages/generator-botkit/CHANGELOG.md, packages/generator-botkit/generators/web/templates/features/typing.js, packages/generator-botkit/package.json
=> Add missing require in generator

packages/botbuilder-adapter-slack/readme.md
controller.getInstallLink() should be adapter.getInstallLink()
=> Fixed getInstallLink() error

packages/botbuilder-adapter-slack/src/slack_adapter.ts
fix typo
action (X) => actions (O)
=> Fix SlackAdapter datepicker typo

packages/botkit/src/conversation.ts, packages/docs/index.json, packages/docs/reference/core.md
Fixes #1879 a typo in onChange() example
=> Fixes #1879 Typo in onChange() example

packages/botbuilder-adapter-web/client/client.js
Introduced in 0fa4a3247be8dd932349038cbd598d032b85aeed
Detected by [LGTM](https://lgtm.com/projects/g/howdyai/botkit/?mode=list&severity=error)
=> Fix syntax error in adapter-web client.js

packages/botkit/src/conversation.ts
=> Parse channelData with mustache in conversations

lib/Botkit.d.ts, lib/Slack_web_api.js
for those wanted to use the new granular oauth scope
=> add ouath v2 access endpoint

packages/botbuilder-adapter-webex/src/botworker.ts, packages/botbuilder-adapter-webex/src/webex_adapter.ts, packages/docs/platforms/webex.md, packages/docs/reference/webex.md, packages/testbot/features/webex_features.js
Add parentId to Webex message, methods for replyInThread and startConversationInThread
=> Add threading for Webex adapter

build/botkit-ci.yml, build/botkit-daily.yml
Fix triggers and build number format.
=> Pipeline .yml tweaks

packages/botkit/src/core.ts, packages/docs/reference/core.md, packages/testbot/custom_express.js
Adds a custom_express.js file to the testbot/ folder.
Adds links in the code and docs.
=> Add sample code demonstrating how to use a custom Express instance
